Updated AC style to hide home page title via clip...
gwu-libraries/academiccommons-theme pull request #36
Opened 2018-11-06 23:47 UTC by retrospec

(re: accessbility-friendly hide of homepage h1; request /issues/35 )

Will also need update block configuration once style has been applied ("Page title" block [admin/structure/block/manage/lai_page_title] -> Pages to show title for all pages).

2018-11-16 20:49 UTC, maxstarkenburg requested changes
This actually hides the h1 on all pages (e.g. see /aauw-selected-professions-fellowships or /beyond-the-classroom), except GW Resource type pages since other CSS for them overrides height/width (though it alters their display too). Despite the filename, homepage.css actually gets pulled in on all pages. I'd think `.path-frontpage h1` would work as a selector.

Much more minor: I'd prefer 2-spaces over tabs (at least to keep consistent with the rest of the .scss), but we can also talk about that if you have a different preference, and I realize other stuff like the PHP is all over the place.

2018-11-16 20:57 UTC, retrospec commented
K. Will review again and apply necessary changes on Monday (11/19).

2018-11-19 16:43 UTC, maxstarkenburg approved these changes

2018-11-19 16:47 UTC, maxstarkenburg commented
Much better, thanks. :cake:

Note to self: just removing `<front>` from restricted pages was apparently not enough (despite the interface claiming there were no longer page restrictions ) ... apparently need to specifically change the "Hide for the listed pages" radio button to the "Show for the listed pages" option instead, or else it just fails to output the title on most all pages.

2018-12-10 18:00 UTC, merged